# Generated by Django 4.2 on 2024-01-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "users_image",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="users/"
                    ),
                ),
            ],
        ),
    ]
